services:
  auth:
    container_name: ms-auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env
    ports:
      - "6000:6000"
    depends_on:
      ms-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6000/api/v1/ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - default

  lumi:
    container_name: ms-lumi
    build:
      context: ./lumi
      dockerfile: Dockerfile
    env_file:
      - ./lumi/.env
    ports:
      - "6060:6060"
    depends_on:
      ms-db:
        condition: service_healthy
      auth:
        condition: service_healthy
      waha:
        condition: service_started
    networks:
      - default

  ms-db:
    image: postgres:latest
    container_name: ms-db
    environment:
      POSTGRES_USER: ms-auth
      POSTGRES_PASSWORD: ms-auth
      POSTGRES_DB: ms-db
    volumes:
      - ms_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ms-auth -d ms-db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - default

  waha:
    container_name: ms-waha
    build:
      context: ./waha
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./waha/.env
    ports:
      - "3000:3000"
    depends_on:
      ms-db:
        condition: service_healthy
    networks:
      - default

volumes:
  ms_db_data:

networks:
  default:
    name: ms-network
    driver: bridge
